// app/layout.tsx
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import StyleRoot from "./StyleRoot";
import { Inter, Roboto_Mono } from "next/font/google";
import Link from "next/link";
import AppLayout from "@/component/appLayout";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Students store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable}`}>
        <AppRouterCacheProvider>
          <StyleRoot>
            <AppLayout> {children}</AppLayout>
          </StyleRoot>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
